### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalAccessException: access violation: class com.worksap.nlp.sudachi.MorphemeImpl, from public Lookup

### ISSUE THREAD

**Issue by azagniotov** [WorksApplications/Sudachi#220]
I am using Sudachi as a Lucene Solr plugin. Something must have changed in Solr starting `v9.4.0` as now I see the exception:

TL;DR
It complains that `class com.worksap.nlp.sudachi.MorphemeImpl` is not public 🤔 

```
2024-02-11 02:17:22.613 ERROR (qtp1331270134-22) [ x:example t:null-1] o.a.s.s.HttpSolrCall 500 Exception => java.lang.RuntimeException: java.lang.IllegalAccessException: access violation: class com.worksap.nlp.sudachi.MorphemeImpl, from public Lookup
	at org.apache.solr.common.util.Utils.getReflectWriter(Utils.java:860)
java.lang.RuntimeException: java.lang.IllegalAccessException: access violation: class com.worksap.nlp.sudachi.MorphemeImpl, from public Lookup
	at org.apache.solr.common.util.Utils.getReflectWriter(Utils.java:860) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:114) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:404) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:312) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:77) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeJsonIter(JsonTextWriter.java:205) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeArray(JsonTextWriter.java:295) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:99) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsFlat(JsonTextWriter.java:508) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:314) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:77) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:404) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:312) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:77) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:404) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:312) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:77) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:404) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:312) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:77) ~[?:?]
	at org.apache.solr.response.TextResponseWriter.writeVal(TextResponseWriter.java:212) ~[?:?]
	at org.apache.solr.common.util.TextWriter.writeVal(TextWriter.java:48) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedListAsMapWithDups(JsonTextWriter.java:404) ~[?:?]
	at org.apache.solr.common.util.JsonTextWriter.writeNamedList(JsonTextWriter.java:312) ~[?:?]
	at org.apache.solr.response.JacksonJsonWriter$WriterImpl.writeResponse(JacksonJsonWriter.java:87) ~[?:?]
	at org.apache.solr.response.JacksonJsonWriter.write(JacksonJsonWriter.java:50) ~[?:?]
	at org.apache.solr.response.QueryResponseWriterUtil.writeQueryResponse(QueryResponseWriterUtil.java:55) ~[?:?]
	at org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:996) ~[?:?]
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:586) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:262) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:219) ~[?:?]
	at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:246) ~[?:?]
	at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:215) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:213) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195) ~[?:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598) ~[jetty-security-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:228) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301) ~[jetty-rewrite-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) ~[jetty-server-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[jetty-io-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[jetty-util-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[jetty-util-10.0.17.jar:10.0.17]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[jetty-util-10.0.17.jar:10.0.17]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalAccessException: access violation: class com.worksap.nlp.sudachi.MorphemeImpl, from public Lookup
	at java.lang.invoke.MethodHandles$Lookup.makeAccessException(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.accessClass(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.Utils.addTraditionalFieldWriters(Utils.java:953) ~[?:?]
	at org.apache.solr.common.util.Utils.getReflectData(Utils.java:912) ~[?:?]
	at org.apache.solr.common.util.Utils.getReflectWriter(Utils.java:847) ~[?:?]
```

**Comment by azagniotov** [comment]
Not an issue. Sorry for the noise!
