### ISSUE TITLE
oovPOS is invalid 

### ISSUE THREAD

**Issue by kira7** [WorksApplications/Sudachi#36]
I tried to start `sudachi` in this way but end up like this.
```
target]$ java -jar sudachi-0.1.1-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalArgumentException: oovPOS is invalid:????,??,*,*,*,*
	at com.worksap.nlp.sudachi.SimpleOovProviderPlugin.setUp(SimpleOovProviderPlugin.java:63)
	at com.worksap.nlp.sudachi.JapaneseDictionary.<init>(JapaneseDictionary.java:89)
	at com.worksap.nlp.sudachi.JapaneseDictionary.<init>(JapaneseDictionary.java:56)
	at com.worksap.nlp.sudachi.DictionaryFactory.create(DictionaryFactory.java:44)
	at com.worksap.nlp.sudachi.SudachiCommandLine.main(SudachiCommandLine.java:135)
```
I've checked the content in `./src/main/resources/sudachi.json` and the `oovProviderPlugin` part seems OK.

**Comment by kazuma-t** [comment]
It seems to be something related the character encoding. Could you try to add -Dfile.encoding=UTF-8 to the command-line arguments?

**Comment by kira7** [comment]
Thanks. I add the option but basically the same. 
```
target]$ java -jar -Dfile.encoding=UTF-8 sudachi-0.1.1-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalArgumentException: oovPOS is invalid:補助記号,一般,*,*,*,*
	at com.worksap.nlp.sudachi.SimpleOovProviderPlugin.setUp(SimpleOovProviderPlugin.java:63)
	at com.worksap.nlp.sudachi.JapaneseDictionary.<init>(JapaneseDictionary.java:89)
	at com.worksap.nlp.sudachi.JapaneseDictionary.<init>(JapaneseDictionary.java:56)
	at com.worksap.nlp.sudachi.DictionaryFactory.create(DictionaryFactory.java:44)
	at com.worksap.nlp.sudachi.SudachiCommandLine.main(SudachiCommandLine.java:135)
```

**Comment by kazuma-t** [comment]
The dictionary seems broken. Does your system work with encoding other than UTF-8? Would you add -Dfile.encoding=UTF-8 to MAVEN_OPTS and rebuild?

**Comment by kira7** [comment]
Great! I should have set it explicitly before building. 
Thanks very much for your help! @kazuma-t

**Comment by kazuma-t** [comment]
Thank you for your report. I'll add a note about the system encoding to README.
